import type { NextPage } from 'next';
import Head from 'next/head';
import Vim from '../components/vim';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Vim />
		</div>
	);
};

export default Home;
